.TH "Main.cpp" 3 "Thu Dec 4 2014" "Rorschach" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ListOfSubstrings\&.h'\fP
.br
\fC#include 'Reader\&.h'\fP
.br
\fC#include 'RKRGST\&.h'\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sys/time\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBASE\fP   2"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char * \fBstring\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBgetTime\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BASE   2"

.PP
Definition at line 35 of file Main\&.cpp\&.
.PP
Referenced by main()\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef char* \fBstring\fP"

.PP
Definition at line 38 of file Main\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "double getTime ()"

.PP
Definition at line 50 of file Main\&.cpp\&.
.PP
Referenced by main()\&.
.SS "int main (intargc, char **argv)"

.PP
Definition at line 58 of file Main\&.cpp\&.
.PP
References BASE, RKRGST< TypeOfContent >::execute(), Reader< TypeOfContent >::filesToBox(), getTime(), Match::length, RKRGST< TypeOfContent >::lengthOfTokensTiled, RKRGST< TypeOfContent >::listOfFinalTiles, ListOfMatches::numberOfMatches, Match::patternIndex, Match::print(), ListOfMatches::remove(), and Match::textIndex\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Rorschach from the source code\&.
