.TH "RKRGST.h" 3 "Thu Dec 4 2014" "Rorschach" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RKRGST.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Box\&.h'\fP
.br
\fC#include 'ListOfTiles\&.h'\fP
.br
\fC#include 'HashTable\&.h'\fP
.br
\fC#include 'ListOfMatches\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRKRGST< TypeOfContent >\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_LENGTH\fP   20"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_LENGTH   20"

.PP
Definition at line 38 of file RKRGST\&.h\&.
.PP
Referenced by RKRGST< TypeOfContent >::execute(), and RKRGST< TypeOfContent >::scanPattern()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Rorschach from the source code\&.
