Rorschach: ListOfMatches Class Reference
ListOfMatches Class Reference
#include <ListOfMatches.h>
Public Member Functions
ListOfMatches ()
void insert (int length, int patternIndex, int textIndex)
Match * remove ()
Public Attributes
int numberOfMatches
Número de casamentos (objetos da classe Match) na lista.
Match * begin
Ponteiro para o início da lista.
Detailed Description
Lista de casamentos (objetos da classe Match)
Definition at line 33 of file ListOfMatches.h.
Constructor & Destructor Documentation
ListOfMatches::ListOfMatches () inline
Construtor de objeto da classe ListOfMatches
Definition at line 43 of file ListOfMatches.h.
Member Function Documentation
void ListOfMatches::insert (int length, int patternIndex, int textIndex)
Insere casamento (objeto da classe Match)
Parameters
length Tamanho do casamento (objeto da classe Match) a ser inserido.
patternIndex Índice em pattern do casamento (objeto da classe Match) a ser inserido.
textIndex Índice em text do casamento (objeto da classe Match) a ser inserido.
Definition at line 26 of file ListOfMatches.cpp.
References begin, Match::length, Match::next, numberOfMatches, and Match::previous.
Referenced by RKRGST< TypeOfContent >::markArrays(), and RKRGST< TypeOfContent >::scanPattern().
Match * ListOfMatches::remove ()
Remove um match da lista
Definition at line 78 of file ListOfMatches.cpp.
References begin, Match::next, numberOfMatches, and Match::previous.
Referenced by main(), and RKRGST< TypeOfContent >::markArrays().
Member Data Documentation
Match* ListOfMatches::begin
Ponteiro para o início da lista.
Definition at line 39 of file ListOfMatches.h.
Referenced by insert(), and remove().
int ListOfMatches::numberOfMatches
Número de casamentos (objetos da classe Match) na lista.
Definition at line 37 of file ListOfMatches.h.
Referenced by insert(), main(), RKRGST< TypeOfContent >::markArrays(), and remove().
The documentation for this class was generated from the following files:
ListOfMatches.h
ListOfMatches.cpp