Rorschach: Reader< TypeOfContent > Class Template Reference
Reader< TypeOfContent > Class Template Reference
#include <Reader.h>
Public Member Functions
Reader (string patternFileName, string textFileName)
void printFiles ()
bool fileExist (const std::string &name)
Box< TypeOfContent > * filesToBox ()
Public Attributes
std::fstream textFile
arquivo que contem o texto
std::fstream patternFile
arquivo que contem o pattern
Detailed Description
template<typename TypeOfContent>
class Reader< TypeOfContent >
Template Parameters
TypeOfContent tipo da letra do alfabeto utilizado. Tipo dos termos de text e pattern tipo usado para a leitura dos arquivos que contem o texto
Definition at line 45 of file Reader.h.
Constructor & Destructor Documentation
template<typename TypeOfContent> Reader< TypeOfContent >::Reader (string patternFileName, string textFileName) inline
Construtor que, atraves dos nomes dos arquivos, os abre.
Parameters
patternFileName nome do arquivo contendo pattern
textFileName nome do arquivo contendo text
Definition at line 60 of file Reader.h.
References Reader< TypeOfContent >::fileExist().
Member Function Documentation
template<typename TypeOfContent> bool Reader< TypeOfContent >::fileExist (const std::string & name) inline
Definition at line 117 of file Reader.h.
Referenced by Reader< TypeOfContent >::Reader().
template<typename TypeOfContent> Box<TypeOfContent>* Reader< TypeOfContent >::filesToBox () inline
através dos arquivos encontrados no construtor, lê cada arquivo e para cada um adiciona seu respectivo conteúdo em um vetor de Letter<char> diferente. Por fim, agrupa-os, junto aos seus tamanhos em um objeto do tipo Box
Returns
box contendo os vetores de Letter<char> criados e seus tamanhos
See also
Letter
Box
Definition at line 141 of file Reader.h.
Referenced by main().
template<typename TypeOfContent> void Reader< TypeOfContent >::printFiles () inline
transforma os dados de um arquivo diretamente no tipo Box Usado quando o dado a ser trabalho eh char. Quando for token, apos a leitura do arquivo eh necessario realizar um passo a mais para a tokenização
Returns
void
Definition at line 85 of file Reader.h.
Member Data Documentation
template<typename TypeOfContent> std::fstream Reader< TypeOfContent >::patternFile
arquivo que contem o pattern
Definition at line 53 of file Reader.h.
template<typename TypeOfContent> std::fstream Reader< TypeOfContent >::textFile
arquivo que contem o texto
Definition at line 49 of file Reader.h.
The documentation for this class was generated from the following file:
Reader.h