Rorschach: RKRGST< TypeOfContent > Class Template Reference
RKRGST< TypeOfContent > Class Template Reference
#include <RKRGST.h>
Public Member Functions
RKRGST (Box< TypeOfContent > *box, int initialSearchLength, int minimumSearchLength, int baseLength)
void execute ()
void markArrays (int searchLength, ListOfMatches *listOfMatches)
int scanPattern (int searchLength, ListOfMatches *listOfMatches)
int findPatternSubstring (int searchLength, HashTable< TypeOfContent > *textHashTable, int actualIndex)
void fillTextHashTable (int searchLength, HashTable< TypeOfContent > *textHashTable)
bool occluded (Box< TypeOfContent > *box, Match *match)
void markTokens (Box< TypeOfContent > *box, Match *match)
Public Attributes
int initialSearchLength
Tamanho inicial do padrão buscado.
int minimumSearchLength
Tamanho mínimo a ser buscado.
int primeNumber
Número primo utilizado na hash.
Box< TypeOfContent > * box
Container de dados que guarda a palavra que compõe a Text, a palavra que contém a Pattern e seus respectivos tamanhos.
ListOfTiles * listOfPatternTiles
Ponteiro para um objeto da classe ListOfTiles que contém uma lista de objetos da classe Tile relativos à Pattern.
ListOfTiles * listOfTextTiles
Ponteiro para um objeto da classe ListOfTiles que contém uma lista de objetos da classe Tile relativos à Text.
int baseLength
Tamanho da base dos números gerados pela RollingHash.
int lengthOfTokensTiled
ListOfMatches * listOfFinalTiles
Detailed Description
template<typename TypeOfContent>
class RKRGST< TypeOfContent >
Template Parameters
TypeOfContent tipo da letra do alfabeto utilizado. Tipo dos termos da pattern e da text Classe contendo todos os algoritmos realizados pelo RKRGST
Definition at line 48 of file RKRGST.h.
Constructor & Destructor Documentation
template<typename TypeOfContent> RKRGST< TypeOfContent >::RKRGST (Box< TypeOfContent > * box, int initialSearchLength, int minimumSearchLength, int baseLength) inline
Construtor de objeto da classe RKRGST
Parameters
box Container de dados que guarda a palavra que compõe a Text, a palavra que contém a Pattern e seus respectivos tamanhos
initialSearchLength Tamanho inicial do padrão buscado
minimumSearchLength Tamanho mínimo a ser buscado
baseLength Tamanho da base dos números gerados pela RollingHash.
Definition at line 86 of file RKRGST.h.
References RKRGST< TypeOfContent >::baseLength, RKRGST< TypeOfContent >::box, RKRGST< TypeOfContent >::initialSearchLength, RKRGST< TypeOfContent >::minimumSearchLength, and RandomPrime::newRandomPrime().
Member Function Documentation
template<typename TypeOfContent> void RKRGST< TypeOfContent >::execute () inline
Método que executa t odo o algoritmo RKRGST
Definition at line 104 of file RKRGST.h.
References RKRGST< TypeOfContent >::initialSearchLength, RKRGST< TypeOfContent >::markArrays(), MAX_LENGTH, RKRGST< TypeOfContent >::minimumSearchLength, and RKRGST< TypeOfContent >::scanPattern().
Referenced by main().
template<typename TypeOfContent> void RKRGST< TypeOfContent >::fillTextHashTable (int searchLength, HashTable< TypeOfContent > * textHashTable) inline
Preenche a tabela de hash do texto com todas as substrings de tamanho searchLength não marcadas
Parameters
searchLength Tamanho das substrings buscadas.
textHashTable Tabela de Hash das subcadeias de text.
See also
HashTable
Definition at line 397 of file RKRGST.h.
References HashTable< TypeOfContent >::addHash(), Substring< TypeOfContent >::append(), RKRGST< TypeOfContent >::baseLength, Tile::begin, ListOfTiles::begin, Substring< TypeOfContent >::begin, Tile::end, Substring< TypeOfContent >::end, Tile::next, Substring< TypeOfContent >::next, Substring< TypeOfContent >::previous, RKRGST< TypeOfContent >::primeNumber, Substring< TypeOfContent >::rollingHash, Substring< TypeOfContent >::skip(), Substring< TypeOfContent >::string, Box< TypeOfContent >::text, and Box< TypeOfContent >::textSize.
Referenced by RKRGST< TypeOfContent >::scanPattern().
template<typename TypeOfContent> int RKRGST< TypeOfContent >::findPatternSubstring (int searchLength, HashTable< TypeOfContent > * textHashTable, int actualIndex) inline
Encontra o índice do início de uma substring de tamanho searchLength. Nenhuma as suas letras podem estar marcadas.
Parameters
searchLength Tamanho das substrings buscadas.
textHashTable Tabela de Hash das subcadeias de text.
actualIndex indice da letra do pattern
Returns
Retorna o índice inicial da substring ou -1 caso não haja substring de tamanho searchLength sem letras marcadas.
Definition at line 319 of file RKRGST.h.
References Tile::begin, ListOfTiles::begin, Tile::end, Tile::next, Box< TypeOfContent >::pattern, and Box< TypeOfContent >::patternSize.
Referenced by RKRGST< TypeOfContent >::scanPattern().
template<typename TypeOfContent> void RKRGST< TypeOfContent >::markArrays (int searchLength, ListOfMatches * listOfMatches) inline
Método que marca as letras de um casamento
Parameters
searchLength Tamanho do casamento.
listOfMatches Casamentos a serem marcados.
Definition at line 157 of file RKRGST.h.
References ListOfMatches::insert(), Match::length, RKRGST< TypeOfContent >::markTokens(), ListOfMatches::numberOfMatches, RKRGST< TypeOfContent >::occluded(), Match::patternIndex, ListOfMatches::remove(), and Match::textIndex.
Referenced by RKRGST< TypeOfContent >::execute().
template<typename TypeOfContent> void RKRGST< TypeOfContent >::markTokens (Box< TypeOfContent > * box, Match * match) inline
Marca os tokens de um casamento
Parameters
box Objeto contendo text, pattern e seus respectivos tamanhos.
match Casamento a ser marcado
Definition at line 637 of file RKRGST.h.
References Match::length, Box< TypeOfContent >::pattern, Match::patternIndex, Box< TypeOfContent >::text, and Match::textIndex.
Referenced by RKRGST< TypeOfContent >::markArrays().
template<typename TypeOfContent> bool RKRGST< TypeOfContent >::occluded (Box< TypeOfContent > * box, Match * match) inline
Verifica se o casamento é ocluso por algum tile.
Parameters
box Objeto contendo text, pattern e seus respectivos tamanhos.
match Casamento a ser verificado
Definition at line 616 of file RKRGST.h.
References Match::length, Box< TypeOfContent >::pattern, Match::patternIndex, Box< TypeOfContent >::text, and Match::textIndex.
Referenced by RKRGST< TypeOfContent >::markArrays().
template<typename TypeOfContent> int RKRGST< TypeOfContent >::scanPattern (int searchLength, ListOfMatches * listOfMatches) inline
Buscando casamentos de tamanho searchLength
Parameters
searchLength Tamanho do casamento sendo buscado.
listOfMatches Lista de casamentos encontrados na scanPattern.
Tabela de Hash contendo as substrings de Text
Definition at line 190 of file RKRGST.h.
References RKRGST< TypeOfContent >::baseLength, Substring< TypeOfContent >::begin, RKRGST< TypeOfContent >::fillTextHashTable(), RKRGST< TypeOfContent >::findPatternSubstring(), ListOfMatches::insert(), MAX_LENGTH, Substring< TypeOfContent >::next, Box< TypeOfContent >::pattern, Box< TypeOfContent >::patternSize, RKRGST< TypeOfContent >::primeNumber, Substring< TypeOfContent >::rollingHash, Substring< TypeOfContent >::string, HashTable< TypeOfContent >::table, and Box< TypeOfContent >::textSize.
Referenced by RKRGST< TypeOfContent >::execute().
Member Data Documentation
template<typename TypeOfContent> int RKRGST< TypeOfContent >::baseLength
Tamanho da base dos números gerados pela RollingHash.
Definition at line 71 of file RKRGST.h.
Referenced by RKRGST< TypeOfContent >::fillTextHashTable(), RKRGST< TypeOfContent >::RKRGST(), and RKRGST< TypeOfContent >::scanPattern().
template<typename TypeOfContent> Box< TypeOfContent >* RKRGST< TypeOfContent >::box
Container de dados que guarda a palavra que compõe a Text, a palavra que contém a Pattern e seus respectivos tamanhos.
Definition at line 62 of file RKRGST.h.
Referenced by RKRGST< TypeOfContent >::RKRGST().
template<typename TypeOfContent> int RKRGST< TypeOfContent >::initialSearchLength
Tamanho inicial do padrão buscado.
Definition at line 54 of file RKRGST.h.
Referenced by RKRGST< TypeOfContent >::execute(), and RKRGST< TypeOfContent >::RKRGST().
template<typename TypeOfContent> int RKRGST< TypeOfContent >::lengthOfTokensTiled
Definition at line 73 of file RKRGST.h.
Referenced by main().
template<typename TypeOfContent> ListOfMatches* RKRGST< TypeOfContent >::listOfFinalTiles
Definition at line 75 of file RKRGST.h.
Referenced by main().
template<typename TypeOfContent> ListOfTiles* RKRGST< TypeOfContent >::listOfPatternTiles
Ponteiro para um objeto da classe ListOfTiles que contém uma lista de objetos da classe Tile relativos à Pattern.
Definition at line 65 of file RKRGST.h.
template<typename TypeOfContent> ListOfTiles* RKRGST< TypeOfContent >::listOfTextTiles
Ponteiro para um objeto da classe ListOfTiles que contém uma lista de objetos da classe Tile relativos à Text.
Definition at line 68 of file RKRGST.h.
template<typename TypeOfContent> int RKRGST< TypeOfContent >::minimumSearchLength
Tamanho mínimo a ser buscado.
Definition at line 56 of file RKRGST.h.
Referenced by RKRGST< TypeOfContent >::execute(), and RKRGST< TypeOfContent >::RKRGST().
template<typename TypeOfContent> int RKRGST< TypeOfContent >::primeNumber
Número primo utilizado na hash.
Definition at line 59 of file RKRGST.h.
Referenced by RKRGST< TypeOfContent >::fillTextHashTable(), and RKRGST< TypeOfContent >::scanPattern().
The documentation for this class was generated from the following file:
RKRGST.h