Rorschach: RandomPrime Class Reference
RandomPrime Class Reference
#include <RandomPrime.h>
Public Member Functions
RandomPrime ()
~RandomPrime ()
bool isPrime (int number)
int newRandomPrime (int min, int max)
Public Attributes
RandomNumber * randomNumber
Ponteiro para a classe que cria um número aleatório, primo ou não.
Detailed Description
Classe que cria um número primo aleatório
Definition at line 30 of file RandomPrime.h.
Constructor & Destructor Documentation
RandomPrime::RandomPrime () inline
Construtor da classe RandomPrime
Definition at line 40 of file RandomPrime.h.
RandomPrime::~RandomPrime () inline
Destrutor da classe RandomPrime
Definition at line 48 of file RandomPrime.h.
References randomNumber.
Member Function Documentation
bool RandomPrime::isPrime (int number) inline
Verifica se um certo número é primo ou não
Parameters
number - número que será verificado
Returns
bool - true caso seja primo e false caso contrário
Definition at line 58 of file RandomPrime.h.
Referenced by newRandomPrime().
int RandomPrime::newRandomPrime (int min, int max) inline
Gera um número primo aleatório
Parameters
min - menor número possível de ser retornado
max - maior número possível de ser retornado
Returns
número primo gerado
Definition at line 76 of file RandomPrime.h.
References isPrime(), and RandomNumber::newRandomNumber().
Referenced by RKRGST< TypeOfContent >::RKRGST().
Member Data Documentation
RandomNumber* RandomPrime::randomNumber
Ponteiro para a classe que cria um número aleatório, primo ou não.
Definition at line 35 of file RandomPrime.h.
Referenced by ~RandomPrime().
The documentation for this class was generated from the following file:
RandomPrime.h